# Generated by Django 2.0.7 on 2018-08-07 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0003_auto_20180806_1155'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('setar_nfe', 'O usuário pode alterar a nfe'), ('permissao_teste', 'Permissao de teste'), ('permissao_2', 'Outra permissão'))},
        ),
    ]
