# Generated by Django 2.0.7 on 2018-08-07 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0004_auto_20180807_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='venda',
            options={'permissions': (('setar_nfe', 'O usuário pode alterar a nfe'), ('permissao_teste', 'Permissao de teste'), ('ver_dashboard', 'O usuário pode visualizar o dashboard'))},
        ),
    ]
