# Generated by Django 2.0.7 on 2018-08-29 14:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produtos', '0001_initial'),
        ('vendas', '0005_auto_20180807_1432'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemdopedido',
            options={'verbose_name_plural': 'Itens do Pedido'},
        ),
        migrations.AlterUniqueTogether(
            name='itemdopedido',
            unique_together={('venda', 'produto')},
        ),
    ]
