# Generated by Django 2.0.7 on 2018-08-29 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendas', '0006_auto_20180829_1114'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='status',
            field=models.CharField(choices=[('ABERTA', 'Aberta'), ('FECHADA', 'Fechada'), ('PROCESSANDO', 'Processando'), ('DESCONHECIDO', 'Descohecido')], default='DC', max_length=2),
        ),
    ]
