# Generated by Django 2.0.7 on 2018-08-29 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0010_auto_20180807_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='pessoa',
            name='telefone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='pessoa',
            unique_together={('first_name', 'telefone')},
        ),
    ]
